import { createElement } from 'lwc';
import PF_InventoryRecordsDatatable from 'c/pF_InventoryRecordsDatatable';

describe('c-p-f-inventory-records-datatable', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-p-f-inventory-records-datatable', {
            is: PF_InventoryRecordsDatatable
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});